### ISSUE TITLE
Intel RealSense support

### ISSUE THREAD

**Issue by stevenPennock** [SpectacularAI/ros#6]
Hi,

first of all my setup:
- ubuntu 22.04 (maybe going to be in a docker container)
- Omron LD-90 AMR
- Omron tm5-900 robot arm (on top of the LD-90)
- Intel RealSense d435 or the new ZED X
- nvidia jetson orin nano (not sure yet but probably)

I want to make it into a mobile manipulator that can get a cup of coffee from the coffee machine.
I was thinking of putting the 3d camera on the robot gripper with MoveIt2 to pick up a cup and use the coffee machine.

Now I would like to use the lidar of the LD-90 in combination with a 3d camera (either the d435 or ZED X) to make a 3d map in real time to detect a cup and other objects and to then be integrated with MoveIt2.

So my question is: is it possible to use SpectacularAI to make a real-time 3d map with a d435 or ZED X and then implement it with MoveIt2?

**Comment by Bercon** [comment]
D435 would need to be D435i model which has IMU to work with our SDK. The ZED X I believe already comes with some sort of SLAM of their own, you could perhaps just use that? We haven't tested that particular ZED camera model. Our SDK would produce a real-time 3D point cloud for you, but integration with Movelt2 you would need to implement yourself

To run our SDK on Jetson Orin you will need the commercial version. To get more information on that please contact us through https://www.spectacularai.com/#contact

We don't really offer project consultation through Github issues, so unfortunately this is all the advice I can provide you
